### ISSUE TITLE
Sketch Icon Error on Sketch version 50!

### ISSUE THREAD

**Issue by anm16** [AMoreaux/Sketch-Icons#39]
I have trouble in making for mask for icon when using plug-in on sketch version 50, could you please send me an updated version to activate this function? Thank u so much : )

**Comment by eksteff** [comment]
I can confirm. Won't insert color mask, tried uninstall/re-install, disable/enable etc.. no luck.

**Comment by AMoreaux** [comment]
what is the problem more precisely. can you send me one or two icons for me to try on my side.

**Comment by anm16** [comment]
Now, your plugin cannot be activated on Sketch version 50. These are my sample icons, you can try them. Hopefully, the fixing version would be available soon. Thank u so much : )

[ic.zip](https://github.com/AMoreaux/Sketch-Icons/files/2008769/ic.zip)

**Comment by AMoreaux** [comment]
What do you mean by « can not be activated » ?

Thank for you icons. The bug related to the mask is now fixed and I will publish a patch in a few days 🙂

**Comment by anm16** [comment]
Nice : ) thank u so much.

**Comment by AMoreaux** [comment]
Hi @anm16, did you try with the last version ? 🙂

**Comment by anm16** [comment]
Hi @AMoreaux. I have tried on Sketch version 50.2; however it still cannot be activated : (

**Comment by AMoreaux** [comment]
What version of OS X  do you use ?

**Comment by anm16** [comment]
10.13.4

**Comment by AMoreaux** [comment]
It can be a conflict with other plugin (sketch focus for example) Try to disable other plugins.

**Comment by anm16** [comment]
Thank u so much : )
